export const CLASSROOM_SECTIONS = [
  {
    title: "April",
    isExam: false,
    items: [
      {
        date: "4/8",
        question: "What phrase symbolizes summer?",
        answer: "A vivid carp streamer"
      },
      {
        date: "4/18",
        question: "What is the proper term for the place where people dumped their waste in the Jomon period?",
        answer: "Middens"
      },
       {
        date: "4/27",
        question: "Which of these is not an algebraic spiral?",
        answer: "A"
      }
    ]
  },
  {
    title: "May Midterms",
    isExam: true,
    items: [
      {
        date: "5/19",
        question: "What is the other common name for 'May Sickness'?",
        answer: "May Blues"
      },
       {
        date: "5/20",
        question: "Which pendulum is used for Foucault's pendulum?",
        answer: "A simple pendulum"
      },
       {
        date: "5/21",
        question: "Which of these is generated by the Pantheon?",
        answer: "Electricity"
      },
       {
        date: "5/22",
        question: "In which historical period were middens most common?",
        answer: "Jomon"
      }
    ]
  },
   {
    title: "June",
    isExam: false,
    items: [
      {
        date: "6/15",
        question: "Which phrase means 'able to see things as they really are'?",
        answer: "Keen eye"
      },
       {
        date: "6/17",
        question: "Which early religious practice was the origin of magic?",
        answer: "Shamanism"
      }
    ]
  }
];
